### ISSUE TITLE
numActions should be numArms in bandit.py

### ISSUE THREAD

**Issue by knbknb** [philtabor/Reinforcement-Learning-In-Motion#2]
In Method `simulate()` in the Bandit class in file `Unit-3-The-Multi-Armed-Bandit/bandit.py`,

 there  exists a call `range(numActions)` but there is no `numActions` defined for this method.
 (numActions is defined as a global variale in the main method, and gets passed in as numArms        
so actually  the result of simulation stays the same. ).

I short, I think that this line

`rewards = [np.random.randn() for _ in range(numActions)]` 
   

should be 

`rewards = [np.random.randn() for _ in range(numArms)]`

Current implementation of the method:

```

def simulate(numArms, epsilon, numPulls):    
    rewardHistory = np.zeros(numPulls)    
    for j in range(2000):
        rewards = [np.random.randn() for _ in range(numActions)]
        bandit = Bandit(numArms, rewards, epsilon)
        if j % 200 == 0:
            print(j)
        for i in range(numPulls):        
            reward = bandit.pull()
            bandit.updateMean(reward)

            rewardHistory[i] += reward
   average = rewardHistory / 2000
   return average
```

**Comment by philtabor** [comment]
Great catch, thanks for that.

I've fixed in my latest commit.
